In [1]:
#Q1  Create a NumPy array 'arr' of integers from 0 to 5 and print its data type. 
import numpy as np
l=[i for i in range(0,6)]
arr=np.array(l)
print(arr)
print(type(arr))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
#Q2  Given a NumPy array 'arr', check if its data type is float64. 
#                   arr = np.array([1.5, 2.6, 3.7])
import numpy as np
arr=np.array([1.5,2.6,3.7])
if arr.dtype==np.float64:
    print("True")
else:
    print("False")

True


In [3]:
#Q3  Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers
import numpy as np
arr=np.array([1+2j,3-4j,4+7j],dtype=np.complex128)
print(arr)
print(arr.dtype)

[1.+2.j 3.-4.j 4.+7.j]
complex128


In [4]:
#Q4  Convert an existing NumPy array 'arr' of integers to float32 data type.
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
new_arr=arr.astype(np.float32)
print(new_arr)
print(new_arr.dtype)

[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]
float32


In [5]:
#Q5 Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision
import numpy as np
arr=np.array([1.5,2.3,44.5,0.7],dtype=np.float64)
print(arr)
print(arr.dtype)
arr2=arr.astype(np.float32)
print(arr2)
print(arr2.dtype)

[ 1.5  2.3 44.5  0.7]
float64
[ 1.5  2.3 44.5  0.7]
float32


In [6]:
#Q6 write a function array_attributes that takes a NumPy array as input and returns its shape, size, and arr data type
import numpy as np
def array_attributes(arr):
    # arr=np.array(arr)
    shp=arr.shape
    siz=arr.size
    dataType=arr.dtype
    return shp,siz,dataType

arr1=np.array([1,2,3,4,5,6])
print(array_attributes(arr1))


((6,), 6, dtype('int32'))


In [7]:
#Q7 Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
import numpy as np
def array_dimension(arr):
    dim=arr.ndim
    return dim

arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("dimension of",arr1,"is",array_dimension(arr1))
print("dimension of",arr2,"is",array_dimension(arr2))

dimension of [1 2 3 4 5] is 1
dimension of [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] is 2


In [8]:
#Q8  Design a function item_size_info that takes a NumPy array as input and returns the item size and the total 
# size in bytes.
import numpy as np
def item_size_info(arr):
    item_size=arr.itemsize
    size_byte=arr.size*item_size
    return item_size,size_byte

arr1=np.array([1,2,3,4,5])
itemSize,itemSizeByte=item_size_info(arr)
print("Item size:",itemSize,"   ","Item Size in Byte:",itemSizeByte)

    

Item size: 8     Item Size in Byte: 32


In [9]:
#Q9 . Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
import numpy as np
def array_strides(arr):
    return arr.strides

arr1=np.array([[1,2,3],[4,5,6]])
print(array_strides(arr1))

(12, 4)


In [10]:
#Q10   Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
# and strides of the array.
import numpy as np
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr1=np.array([[1,2,3],[4,5,6]])
shape_arr,strides_arr=shape_stride_relationship(arr1)
print("shape of arr",shape_arr)
print("strides of arr",strides_arr)

shape of arr (2, 3)
strides of arr (12, 4)


In [11]:
#Q11  Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of 
# zeros with `n` elements.
import numpy as np
def create_zeros_array(n):
    arr=np.zeros(n,dtype=int)
    return arr

create_zeros_array(5)

array([0, 0, 0, 0, 0])

In [12]:
#Q12 Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
# NumPy array filled with ones of size `rows x cols`.
import numpy as np
def create_ones_matrix(rows,cols):
    arr=np.ones(shape=(rows,cols),dtype=int)
    return arr
create_ones_matrix(3,2)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [13]:
#Q13 Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 
# `step`.
import numpy as np
def generate_range_array(start,stop,step):
    arr=np.arange(start,stop,step)
    return arr

generate_range_array(1,5,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9])

In [14]:
#Q14  Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
# (inclusive)
import numpy as np
def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)

start=0.0
stop=1.0
num=5
print(generate_linear_space(start,stop,num))

[0.   0.25 0.5  0.75 1.  ]


In [15]:
#Q15 Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
# identity matrix of size `n x n` using `numpy.eye`
import numpy as np
def create_identity_matrix(n):
    return np.eye(n)
n=4
print(create_identity_matrix(n))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
#Q16 . Write a function that takes a Python list and converts it into a NumPy array.
import numpy as np
def list_to_numpyArray(l):
    return np.array(l)
l=[1,2,3,4,5]
print(list_to_numpyArray(l))
print()
l2=[[1,2,3,4],[5,6,7,8]]
print(list_to_numpyArray(l2))

[1 2 3 4 5]

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
#Q17  Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the 
# same data
import numpy as np
l=[1,2,3,4]
arr=np.array(l)
print("original array",arr)
view_array=arr.view()
view_array[0]=7
print("view array",view_array)

original array [1 2 3 4]
view array [7 2 3 4]


In [18]:
#Q18  Write a function that takes two NumPy arrays and concatenates them along a specified axis.
import numpy as np
def concate_array(arr1,arr2):
    return np.concatenate((arr1,arr2),axis=0)

arr1=np.array([[1,2,3,4]])
arr2=np.array([[5,6,7,8]])

print(concate_array(arr1,arr2))

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
#Q19 Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
#  concatenate
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6,7],[8,9,10]])
result=np.concatenate((arr1,arr2),axis=1)

print("array1")
print(arr1)
print("array2")
print(arr2)
print("result")
print(result)


array1
[[1 2]
 [3 4]]
array2
[[ 5  6  7]
 [ 8  9 10]]
result
[[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


In [20]:
#Q20    Write a function that vertically stacks multiple NumPy arrays given as a list
import numpy as np
def stack_arrays_vetically(l):
    return np.vstack(l)

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr3=np.array([[9,10],[11,12]])

arr_list=[arr1,arr2,arr3]

print(stack_arrays_vetically(arr_list))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [21]:
#Q21 Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
# with a given step size

import numpy as np
def create_int_array(start,end,step):
    result=np.arange(start,end+1,step,dtype=int)
    return result
start,end,step=1,10,2
print(create_int_array(start,end,step))

[1 3 5 7 9]


In [22]:
#Q22 Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 
# (inclusive)
import numpy as np
def generate_array():
    return np.arange(0,1,0.1)
generate_array()

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [23]:
#Q23 Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 
# 1000 (inclusive)
import numpy as np
def generate_log(start,stop,num):
    return  np.logspace(np.log10(start), np.log10(stop), num, endpoint=True)

generate_log(1,1000,5)

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [24]:

#Q24 Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
# are random integers between 1 and 100.
import numpy as np
import pandas as pd

# Create a NumPy array with random integers between 1 and 100
random_array = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame using the random array
df = pd.DataFrame(random_array, columns=['Column 1', 'Column 2', 'Column 3'])

print("Pandas DataFrame:")
print(df)


Pandas DataFrame:
   Column 1  Column 2  Column 3
0        11        68        25
1        84        21        95
2        50        40        57
3        54        35        39
4        92         4        17


In [25]:
#Q25 Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
# with zeros. Use NumPy operations within the Pandas DataFrame.
import pandas as pd
import numpy as np

def replace_negatives_with_zeros(df, column_name):
    # Use NumPy operations to replace negative values with zeros in the specified column
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage:
# Create a sample DataFrame
data = {'A': [1, 2, -3, 4, -5],
        'B': [5, -6, 7, -8, 9]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Replace negative values in column 'A' with zeros
df = replace_negatives_with_zeros(df, 'A')

print("\nDataFrame after replacing negative values in column 'A' with zeros:")
print(df)


Original DataFrame:
   A  B
0  1  5
1  2 -6
2 -3  7
3  4 -8
4 -5  9

DataFrame after replacing negative values in column 'A' with zeros:
   A  B
0  1  5
1  2 -6
2  0  7
3  4 -8
4  0  9


In [26]:
#Q26 Access the 3rd element from the given NumPy array.
#  arr = np.array([10, 20, 30, 40, 50])
import numpy as np
arr=np.array([10,20,30,40,50])
print(f"third element of arrray is ",arr[2])

third element of arrray is  30


In [27]:
#Q27  Retrieve the element at index (1, 2) from the 2D NumPy array.
#  arr_2d = np.array([[1, 2, 3],
#                     [4, 5, 6],
#                     [7, 8, 9]])
import numpy as np
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])


print(f"enelent at index (1,2) of {arr_2d} array is {arr_2d[1][2]}")

enelent at index (1,2) of [[1 2 3]
 [4 5 6]
 [7 8 9]] array is 6


In [28]:
#Q28 Using boolean indexing, extract elements greater than 5 from the given NumPy array.
#  arr = np.array([3, 8, 2, 10, 5, 7])
import numpy as np
arr = np.array([3, 8, 2, 10, 5, 7])
greater=arr[arr>5]
print(greater)

[ 8 10  7]


In [29]:
#Q29  Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
#  arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_arr=arr[2:5]
print(sliced_arr)

[3 4 5]


In [30]:
#Q30 Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
# arr_2d = np.array([[1, 2, 3],
#  [4, 5, 6],
#  [7, 8, 9]])
import numpy as np

arr_2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

sliced_arr_2d=arr_2d[0:2,1:3]
print(sliced_arr_2d)


[[2 3]
 [5 6]]


In [31]:
#Q31 Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
# provided in another array.
import numpy as np

def extract_elements(arr_2d, indices):
    # Convert indices to a NumPy array if it's not already
    indices = np.array(indices)
    # Use advanced indexing to extract elements based on indices
    extracted_elements = arr_2d[indices[:,0], indices[:,1]]
    return extracted_elements

# Example usage:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([[0, 1],
                    [1, 2]])

extracted_elements = extract_elements(arr_2d, indices)
print("Extracted elements based on indices:", extracted_elements)


Extracted elements based on indices: [2 6]


In [32]:
#Q32  Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
# boolean indexing
import numpy as np

def filter_elements(arr, threshold):
    filtered_elements = arr[arr > threshold]
    return filtered_elements

# Example usage:
arr = np.array([1, 3, 5, 7, 9, 11, 13])
threshold = 5

filtered_array = filter_elements(arr, threshold)
print("Filtered elements greater than", threshold, ":", filtered_array)


Filtered elements greater than 5 : [ 7  9 11 13]


In [33]:
#Q33  Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
# separate arrays for each dimension
import numpy as np

def extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3):
    # Convert indices to NumPy arrays if they're not already
    indices_dim1 = np.array(indices_dim1)
    indices_dim2 = np.array(indices_dim2)
    indices_dim3 = np.array(indices_dim3)
    
    # Use advanced indexing to extract elements based on indices
    extracted_elements = arr_3d[indices_dim1, indices_dim2, indices_dim3]
    return extracted_elements

# Example usage:
arr_3d = np.arange(24).reshape((2, 3, 4))  # Example 3D array
indices_dim1 = [0, 1]  # Indices for the first dimension
indices_dim2 = [0, 2]  # Indices for the second dimension
indices_dim3 = [1, 3]  # Indices for the third dimension

extracted_elements = extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print("Extracted elements from the 3D array:", extracted_elements)


Extracted elements from the 3D array: [ 1 23]


In [34]:
#Q34  Write a NumPy function that returns elements from an array where both two conditions are satisfied 
# using boolean indexing.

import numpy as np

def filter_elements_two_conditions(arr, condition1, condition2):
    # Use boolean indexing to filter elements that satisfy both conditions
    filtered_elements = arr[condition1 & condition2]
    return filtered_elements

# Example usage:
arr = np.array([1, 3, 5, 7, 9, 11, 13, 15])

# Define two conditions
condition1 = arr > 5
condition2 = arr < 13

filtered_array = filter_elements_two_conditions(arr, condition1, condition2)
print("Filtered elements that satisfy both conditions:", filtered_array)



Filtered elements that satisfy both conditions: [ 7  9 11]


In [35]:
#Q35 Create a NumPy function that extracts elements from a 2D array using row and column indices provided 
# in separate arrays.
import numpy as np

def extract_elements_2d(arr_2d, row_indices, col_indices):
    # Convert indices to NumPy arrays if they're not already
    row_indices = np.array(row_indices)
    col_indices = np.array(col_indices)
    
    # Use advanced indexing to extract elements based on row and column indices
    extracted_elements = arr_2d[row_indices, col_indices]
    return extracted_elements

# Example usage:
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

row_indices = [0, 1, 2]  # Indices for the rows
col_indices = [1, 2, 0]  # Indices for the columns

extracted_elements = extract_elements_2d(arr_2d, row_indices, col_indices)
print("Extracted elements from the 2D array:", extracted_elements)


Extracted elements from the 2D array: [20 60 70]


In [36]:
#Q36  Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a scalar value of 5 to each element
result = arr + 5

print("Original array:")
print(arr)
print("\nArray after adding 5 to each element:")
print(result)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after adding 5 to each element:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
#Q37 Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
# corresponding element in arr1 using NumPy broadcasting.
import numpy as np

# Define the arrays
arr1 = np.array([[2, 3, 4]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  # Shape (3, 4)

# Reshape arr1 to be compatible with arr2 for broadcasting
arr1_reshaped = arr1.T  # Shape (3, 1)

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr1_reshaped * arr2

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult after broadcasting multiplication:")
print(result)


Array arr1:
[[2 3 4]]

Array arr2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result after broadcasting multiplication:
[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [38]:
#Q38 . Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using 
# NumPy broadcasting.
import numpy as np

# Define the arrays
arr1 = np.array([1, 2, 3, 4])  # Shape (1, 4)
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])  # Shape (4, 3)

# Adjust arr1 to be broadcastable for addition to each row of arr2
# Here we are assuming you intended to add first 3 elements of arr1 to each row of arr2
arr1 = arr1[:3]  # Shape (3,)

# Add arr1 to each row of arr2 using broadcasting
result = arr2 + arr1

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult after broadcasting addition:")
print(result)


Array arr1:
[1 2 3]

Array arr2:
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]

Result after broadcasting addition:
[[ 6  8 10]
 [ 9 11 13]
 [12 14 16]
 [15 17 19]]


In [39]:
#Q 39 Add two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3) using NumPy broadcasting:
import numpy as np

# Define the arrays
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])

# Use broadcasting to add the arrays
result = arr1 + arr2

print("Result of adding arr1 and arr2 using broadcasting:")
print(result)


Result of adding arr1 and arr2 using broadcasting:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [40]:
#Q40 Perform multiplication of arrays arr1 of shape (2, 3) and arr2 of shape (2, 2) using NumPy broadcasting, handling the shape incompatibility:
import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

# Since arr1.shape is (2, 3) and arr2.shape is (2, 2), we cannot directly multiply them.
# We can reshape arr2 to be broadcastable with arr1 or use a different approach depending on the use case.

# Option 1: Reshape arr2 to match arr1 shape (This is a specific solution and assumes a repetitive pattern for arr2)
arr2_resized = np.hstack((arr2, arr2[:, :1]))  # Reshape to (2, 3) by repeating last column

# Perform element-wise multiplication using broadcasting
result = arr1 * arr2_resized

print("Result of multiplying arr1 and arr2_resized using broadcasting:")
print(result)


Result of multiplying arr1 and arr2_resized using broadcasting:
[[ 7 16 21]
 [36 50 54]]


In [41]:
#Q41 Calculate column-wise mean for the given array:
#  arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Calculate column-wise mean
column_mean = np.mean(arr, axis=0)

print("Column-wise mean:")
print(column_mean)


Column-wise mean:
[2.5 3.5 4.5]


In [42]:
#Q42 Find maximum value in each row of the given array:
#  arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Find maximum value in each row
row_max = np.max(arr, axis=1)

print("Maximum value in each row:")
print(row_max)


Maximum value in each row:
[3 6]


In [43]:
#Q43 Find indices of maximum value in each column of the given array:
#  arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])


indices_max = np.argmax(arr, axis=0)

print("Indices of maximum value in each column:")
print(indices_max)


Indices of maximum value in each column:
[1 1 1]


In [44]:
#Q44 Apply custom function to calculate moving sum along rows of the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Define a custom function to calculate moving sum along rows
def moving_sum(arr):
    return np.cumsum(arr, axis=1)

# Apply the custom function
moving_sum_result = moving_sum(arr)

print("Moving sum along rows:")
print(moving_sum_result)


Moving sum along rows:
[[ 1  3  6]
 [ 4  9 15]]


In [45]:
#Q45 Check if all elements in each column are even in the given array:
#  arr = np.array([[2, 4, 6], [3, 5, 7]])
import numpy as np

arr = np.array([[2, 4, 6], [3, 5, 7]])

# Check if all elements in each column are even
all_even_columns = np.all(arr % 2 == 0, axis=0)

print("Are all elements in each column even?")
print(all_even_columns)


Are all elements in each column even?
[False False False]


In [46]:
#Q46 Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the 
# reshaped matrix.
#  original_array = np.array([1, 2, 3, 4, 5, 6])

import numpy as np

def reshape_array(arr, m, n):
    return np.reshape(arr, (m, n))

# Example usage
original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_matrix = reshape_array(original_array, 2, 3)
print("Reshaped Matrix:")
print(reshaped_matrix)



Reshaped Matrix:
[[1 2 3]
 [4 5 6]]


In [47]:
#Q47 Create a function that takes a matrix as input and returns the flattened array.
#  input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()

# Example usage
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print("Flattened Array:")
print(flattened_array)
 

Flattened Array:
[1 2 3 4 5 6]


In [48]:
#Q48 Write a function that concatenates two given arrays along a specified axis.
#  array1 = np.array([[1, 2], [3, 4]])
#  array2 = np.array([[5, 6], [7, 8]])
import numpy as np

def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)

# Example usage
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array = concatenate_arrays(array1, array2, axis=0)
print("Concatenated Array along axis 0:")
print(concatenated_array)


Concatenated Array along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
#Q49  Create a function that splits an array into multiple sub-arrays along a specified axis.
#  original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
import numpy as np

def split_array(array, indices, axis):
    return np.split(array, indices, axis=axis)

# Example usage
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_arrays = split_array(original_array, [1], axis=0)
print("Split Arrays:")
for sub_array in split_arrays:
    print(sub_array)


Split Arrays:
[[1 2 3]]
[[4 5 6]
 [7 8 9]]


In [50]:
#Q50 Write a function that inserts and then deletes elements from a given array at specified indices.
#  original_array = np.array([1, 2, 3, 4, 5])
#  indices_to_insert = [2, 4]
#  values_to_insert = [10, 11]
#  indices_to_delete = [1, 3]
import numpy as np

def insert_and_delete_elements(arr, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements
    arr = np.insert(arr, indices_to_insert, values_to_insert)
    # Delete elements
    arr = np.delete(arr, indices_to_delete)
    return arr

# Example usage
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
modified_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Modified Array:")
print(modified_array)


Modified Array:
[ 1 10  4 11  5]


In [51]:
#Q51  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
# Perform element-wise addition between `arr1` and `arr2`.
import numpy as np

arr1 = np.random.randint(1, 11, size=10)
arr2 = np.arange(1, 11)

# Perform element-wise addition
result = arr1 + arr2

print("Element-wise addition result:")
print(result)


Element-wise addition result:
[ 6  3  9  5 10 16  9 13 18 15]


In [52]:
#Q 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
# from 1 to 10. Subtract `arr2` from `arr1` element-wise.
import numpy as np

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

# Perform element-wise subtraction
result = arr1 - arr2

print("Element-wise subtraction result:")
print(result)


Element-wise subtraction result:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [53]:
#Q 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
# Perform element-wise multiplication between `arr1` and `arr2`.
import numpy as np

arr1 = np.random.randint(1, 11, size=5)
arr2 = np.arange(1, 6)

# Perform element-wise multiplication
result = arr1 * arr2

print("Element-wise multiplication result:")
print(result)


Element-wise multiplication result:
[ 5 14 27 20 35]


In [54]:
#Q 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
# to 5. Perform element-wise division of `arr1` by `arr2`.
import numpy as np

arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)

# Perform element-wise division
result = arr1 / arr2

print("Element-wise division result:")
print(result)


Element-wise division result:
[2. 2. 2. 2. 2.]


In [55]:
#Q55  Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
import numpy as np

arr1 = np.arange(1, 6)
arr2 = np.arange(5, 0, -1)

# Perform element-wise exponentiation
result = np.power(arr1, arr2)

print("Element-wise exponentiation result:")
print(result)


Element-wise exponentiation result:
[ 1 16 27 16  5]


In [56]:
#Q 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
#  arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
import numpy as np

def count_substring_occurrences(arr, substring):
    return np.char.count(arr, substring)

# Example usage
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
occurrences = count_substring_occurrences(arr, substring)
print("Occurrences of substring 'hello':")
print(occurrences)


Occurrences of substring 'hello':
[1 0 1 0 1]


In [57]:
#Q57  Write a function that extracts uppercase characters from a NumPy array of strings.
#  arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
#  arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
import numpy as np

def extract_uppercase(arr):
    return np.char.join('', np.char.upper(np.char.array(list(arr))))

# Example usage
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_characters = extract_uppercase(arr)
print("Uppercase characters extracted:")
print(uppercase_characters)



Uppercase characters extracted:
['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [58]:
#Q58  Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
#  arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
replaced_arr = replace_substring(arr, 'apple', 'fruit')
print("Replaced Array:")
print(replaced_arr)


Replaced Array:
['fruit' 'banana' 'grape' 'pinefruit']


In [59]:
#Q59 Write a function that concatenates strings in a NumPy array element-wise.
#  arr1 = np.array(['Hello', 'World'])
#  arr2 = np.array(['Open', 'AI'])
import numpy as np

def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

# Example usage
arr1 = np.array(['apple', 'banana'])
arr2 = np.array([' pie', ' split'])
concatenated_arr = concatenate_strings(arr1, arr2)
print("Concatenated Strings:")
print(concatenated_arr)


Concatenated Strings:
['apple pie' 'banana split']


In [60]:
#  Q60. Write a function that finds the length of the longest string in a NumPy array.
#  arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
import numpy as np

def length_of_longest_string(arr):
    return np.max(np.char.str_len(arr))

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = length_of_longest_string(arr)
print("Length of the longest string:")
print(longest_length)


Length of the longest string:
9


In [61]:
#Q 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
# standard deviation of the dataset using NumPy's functions.
import numpy as np

# Generate dataset
dataset = np.random.randint(1, 1001, size=100)

# Compute statistics
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Mean: 477.59
Median: 463.5
Variance: 81886.40190000001
Standard Deviation: 286.15800163546015


In [62]:
#62 Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset:
import numpy as np

# Generate dataset
dataset = np.random.randint(1, 101, size=50)

# Compute percentiles
percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


25th Percentile: 36.0
75th Percentile: 71.75


In [63]:
#Q63  Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
# arrays using NumPy's `corrcoef` function
import numpy as np

# Create datasets
x = np.random.randint(1, 101, size=50)
y = np.random.randint(1, 101, size=50)

# Compute correlation coefficient
correlation_matrix = np.corrcoef(x, y)

print("Correlation Coefficient Matrix:")
print(correlation_matrix)


Correlation Coefficient Matrix:
[[ 1.         -0.09234957]
 [-0.09234957  1.        ]]


In [64]:
#Q64Create two matrices and perform matrix multiplication using NumPy's `dot` function
import numpy as np

# Create matrices
matrix1 = np.random.randint(1, 10, size=(3, 3))
matrix2 = np.random.randint(1, 10, size=(3, 3))

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print("Matrix Multiplication Result:")
print(result)


Matrix Multiplication Result:
[[190 165 108]
 [143 104  87]
 [ 94  57  66]]


In [65]:
#Q65  Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
# percentiles along with the first and third quartiles.
import numpy as np

# Generate dataset
dataset = np.random.randint(10, 1001, size=50)

# Compute percentiles and quartiles
percentile_10 = np.percentile(dataset, 10)
percentile_50 = np.percentile(dataset, 50)
percentile_90 = np.percentile(dataset, 90)
first_quartile = np.percentile(dataset, 25)
third_quartile = np.percentile(dataset, 75)

print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile:", first_quartile)
print("Third Quartile:", third_quartile)


10th Percentile: 134.7
50th Percentile (Median): 570.5
90th Percentile: 913.2
First Quartile: 248.0
Third Quartile: 779.0


In [66]:
#Q66 . Create a NumPy array of integers and find the index of a specific element
import numpy as np

def find_index(arr, element):
    index = np.where(arr == element)
    return index[0][0] if index[0].size > 0 else -1

# Example usage
arr = np.array([10, 20, 30, 40, 50])
element = 30
index = find_index(arr, element)
print("Index of element 30:", index)


Index of element 30: 2


In [67]:
#Q67 Generate a random NumPy array and sort it in ascending order.
import numpy as np

# Generate dataset
arr = np.random.randint(1, 101, size=10)

# Sort array
sorted_arr = np.sort(arr)

print("Sorted Array:")
print(sorted_arr)


Sorted Array:
[22 25 31 32 53 73 82 91 92 96]


In [68]:
#Q68  Filter elements >20  in the given NumPy array.
#  arr = np.array([12, 25, 6, 42, 8, 30])
import numpy as np

# Given array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_arr = arr[arr > 20]

print("Filtered elements > 20:")
print(filtered_arr)


Filtered elements > 20:
[25 42 30]


In [69]:
#Q69 Filter elements which are divisible by 3 from a given NumPy array.
#  arr = np.array([1, 5, 8, 12, 15])
import numpy as np

# Given array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]

print("Filtered elements divisible by 3:")
print(filtered_arr)


Filtered elements divisible by 3:
[12 15]


In [70]:
#Q70  Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
#  arr = np.array([10, 20, 30, 40, 50])
import numpy as np

# Given array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements between 20 and 40 inclusive
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print("Filtered elements between 20 and 40:")
print(filtered_arr)


Filtered elements between 20 and 40:
[20 30 40]


In [71]:
#Q71  For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
#  arr = np.array([1, 2, 3])
import numpy as np

# Given array
arr = np.array([1, 2, 3])

# Check byte order
byte_order = arr.dtype.byteorder

print("Byte order of the array:")
print(byte_order)


Byte order of the array:
=


In [72]:
#Q72  For the given NumPy array, perform byte swapping in place using `byteswap()`.
#  arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np

# Given array
arr = np.array([1, 2, 3], dtype=np.int16)

# Perform byte swapping in place
arr.byteswap(True)

print("Array after byte swapping in place:")
print(arr)


Array after byte swapping in place:
[256 512 768]


In [73]:
#Q73  For the given NumPy array, swap its byte order without modifying the original array using 
# `newbyteorder()`.
#  arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np

# Given array
arr = np.array([1, 2, 3], dtype=np.int16)

# Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()

print("Original array:")
print(arr)
print("Array with swapped byte order:")
print(swapped_arr)


Original array:
[1 2 3]
Array with swapped byte order:
[256 512 768]


In [74]:
#Q74 . For the given NumPy array and swap its byte order conditionally based on system endianness using 
# `newbyteorder()`.
#  arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np

# Given array
arr = np.array([1, 2, 3], dtype=np.int16)

# Check system endianness and swap byte order if necessary
if arr.dtype.byteorder == '=':
    swapped_arr = arr.newbyteorder('S')
else:
    swapped_arr = arr

print("Conditionally swapped array:")
print(swapped_arr)


Conditionally swapped array:
[256 512 768]


In [75]:
#Q75 For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
# attribute `byteorder`.
#  arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np

# Given array
arr = np.array([1, 2, 3], dtype=np.int16)

# Check if byte swapping is necessary
byte_order = arr.dtype.byteorder
need_swap = byte_order == '='

print("Is byte swapping necessary?")
print(need_swap)


Is byte swapping necessary?
True


In [76]:
#Q76  Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
import numpy as np

# Create arr1
arr1 = np.arange(1, 11)

# Create a copy of arr1
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

print("Original array (arr1):")
print(arr1)
print("Modified copy (copy_arr):")
print(copy_arr)


Original array (arr1):
[ 1  2  3  4  5  6  7  8  9 10]
Modified copy (copy_arr):
[100   2   3   4   5   6   7   8   9  10]


In [77]:
#Q77  Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
import numpy as np

# Create matrix
matrix = np.random.randint(1, 10, size=(3, 3))

# Extract a slice
view_slice = matrix[:2, :2]

# Modify an element in view_slice
view_slice[0, 0] = 100

print("Original matrix after modifying view_slice:")
print(matrix)


Original matrix after modifying view_slice:
[[100   1   4]
 [  3   4   1]
 [  5   9   4]]


In [78]:
#Q78  Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
import numpy as np

# Create array_a
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice view_b
view_b = array_a[:2, :2]

# Broadcast addition of 5
view_b += 5

print("Original array_a after broadcasting addition to view_b:")
print(array_a)


Original array_a after broadcasting addition to view_b:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


In [79]:
#Q79 . Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
# reflects changes in the original `orig_array`
import numpy as np

# Create orig_array
orig_array = np.arange(1, 9).reshape(2, 4)

# Create reshaped view
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 100

print("Original orig_array after modifying reshaped_view:")
print(orig_array)


Original orig_array after modifying reshaped_view:
[[100   2   3   4]
 [  5   6   7   8]]


In [80]:
#Q80  Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
import numpy as np

# Create data
data = np.random.randint(1, 10, size=(3, 4))

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Modify an element in data_copy
if data_copy.size > 0:
    data_copy[0] = 100

print("Original data:")
print(data)
print("Modified data_copy:")
print(data_copy)


Original data:
[[8 4 3 8]
 [4 2 2 6]
 [1 4 1 6]]
Modified data_copy:
[100   8   6   6]


In [81]:
#Q81 Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
# operations between them.
import numpy as np

# Create matrices A and B
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

# Perform addition
addition_result = A + B

# Perform subtraction
subtraction_result = A - B

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Addition Result:")
print(addition_result)
print("Subtraction Result:")
print(subtraction_result)


Matrix A:
[[5 4 7]
 [3 6 8]
 [6 1 5]]
Matrix B:
[[4 1 3]
 [1 3 4]
 [1 6 6]]
Addition Result:
[[ 9  5 10]
 [ 4  9 12]
 [ 7  7 11]]
Subtraction Result:
[[ 1  3  4]
 [ 2  3  4]
 [ 5 -5 -1]]


In [82]:
#Q82 . Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication
import numpy as np

# Create matrices C and D
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))

# Perform matrix multiplication
multiplication_result = np.dot(C, D)

print("Matrix C:")
print(C)
print("Matrix D:")
print(D)
print("Matrix Multiplication Result:")
print(multiplication_result)


Matrix C:
[[5 9]
 [6 5]
 [6 6]]
Matrix D:
[[3 7 6 2]
 [7 6 9 7]]
Matrix Multiplication Result:
[[ 78  89 111  73]
 [ 53  72  81  47]
 [ 60  78  90  54]]


In [83]:
#Q83  Create a matrix `E` and find its transpose
import numpy as np

# Create matrix E
E = np.random.randint(1, 10, size=(3, 3))

# Find transpose
transpose_E = np.transpose(E)

print("Matrix E:")
print(E)
print("Transpose of E:")
print(transpose_E)


Matrix E:
[[7 4 4]
 [5 5 7]
 [8 6 8]]
Transpose of E:
[[7 5 8]
 [4 5 6]
 [4 7 8]]


In [84]:
#Q84 . Generate a square matrix `F` and compute its determinant.
import numpy as np

# Create square matrix F
F = np.random.randint(1, 10, size=(3, 3))

# Compute determinant
det_F = np.linalg.det(F)

print("Matrix F:")
print(F)
print("Determinant of F:")
print(det_F)


Matrix F:
[[9 3 4]
 [9 5 8]
 [7 9 8]]
Determinant of F:
-152.00000000000014


In [85]:
#Q85 Create a square matrix `G` and find its inverse
import numpy as np

# Create square matrix G
G = np.random.randint(1, 10, size=(3, 3))

# Find inverse
try:
    inverse_G = np.linalg.inv(G)
    print("Matrix G:")
    print(G)
    print("Inverse of G:")
    print(inverse_G)
except np.linalg.LinAlgError:
    print("Matrix G is singular and cannot be inverted.")


Matrix G:
[[7 3 9]
 [5 4 9]
 [4 3 6]]
Inverse of G:
[[ 0.25       -0.75        0.75      ]
 [-0.5        -0.5         1.5       ]
 [ 0.08333333  0.75       -1.08333333]]
